name: KeepAlive

on:
 schedule:
 - cron: 0 3 1 * *
 workflow_dispatch:

 defaults:
  run:
   shell: bash

jobs:
 KeepAlive:

 - name: Try
   run: curl -i -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.ANTALASKAYA_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/keepalive.yml/enable
