# TODO move to separate, less active repo and observe results
name: KeepAlive

on:
 schedule:
 - cron: 0 3 1 * *
 workflow_dispatch:

defaults:
 run:
  shell: bash

jobs:
 KeepAlive:
  runs-on: ubuntu-latest
  steps:

  - name: Self
    run:  |
          curl -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.ANTALASKAYA_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/keepalive.yml/enable

  - name: Schedule
    run:  |
          curl -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.ANTALASKAYA_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/schedule.yml/enable

